"""refactor_user_profile_site_to_site_id_field

Revision ID: 1c3885f4803b
Revises: b41c867b1e65
Create Date: 2025-10-24 19:17:37.705433

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c3885f4803b'
down_revision = 'b41c867b1e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_site_profile_id'), table_name='user_profile_site')
    op.drop_index(op.f('ix_user_profile_site_site_id'), table_name='user_profile_site')
    op.drop_table('user_profile_site')
    op.add_column('user_profile', sa.Column('site_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_user_profile_site_id'), 'user_profile', ['site_id'], unique=False)
    op.create_foreign_key(None, 'user_profile', 'site', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_index(op.f('ix_user_profile_site_id'), table_name='user_profile')
    op.drop_column('user_profile', 'site_id')
    op.create_table('user_profile_site',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('role_in_site', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('user_profile_site_profile_id_fkey')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('user_profile_site_site_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profile_site_pkey'))
    )
    op.create_index(op.f('ix_user_profile_site_site_id'), 'user_profile_site', ['site_id'], unique=False)
    op.create_index(op.f('ix_user_profile_site_profile_id'), 'user_profile_site', ['profile_id'], unique=False)
    # ### end Alembic commands ###
